spring:
  servlet:
    multipart:
      enabled: on
      max-file-size: 512MB
      max-request-size: 1024MB
      location: ${java.io.tmpdir}
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql:///${DB_NAME}?cloudSqlInstance=${INSTANCE_CONNECTION_NAME}&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    username: ${DB_USER}
    password: ${DB_PASS}

server:
  port: 8081
  error:
    include-stacktrace: never
  servlet:
    encoding:
      enabled: on
      force: on
      charset: UTF-8
