spring:
  http:
    encoding:
      charset: UTF-8
      enabled: on
      force: on
  servlet:
    multipart:
      enabled: on
      max-file-size: 64MB
      max-request-size: 128MB
      location: ${java.io.tmpdir}
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://hostname/database?serverTimezone=UTC&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: xxxxxxxxx
    password: xxxxxxxxx
  security:
    user:
      name: xxxxxxxxx
      password: xxxxxxxxx
      roles:
        - USER
        - ADMIN

server:
  port: 8081
  error:
    include-stacktrace: never

api:
  name: Tomlin
  version: 1.0.0
  baseUrl: https://tomlin.no
  auth:
    key: xxxxxxxxx
  tmdb:
    key: xxxxxxxxx
    url: https://api.themoviedb.org/3/
    img: https://image.tmdb.org/t/p/w200
  db:
    backup: -u user -ppassword database
