spring:
  servlet:
    multipart:
      enabled: on
      max-file-size: 512MB
      max-request-size: 1024MB
      location: ${java.io.tmpdir}
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://hostname/database?serverTimezone=Europe/Oslo&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: xxxxxxxxx
    password: xxxxxxxxx
  security:
    user:
      name: xxxxxxxxx
      password: xxxxxxxxx
      roles:
        - USER
        - ADMIN

server:
  port: 8081
  error:
    include-stacktrace: never
  servlet:
    encoding:
      enabled: on
      force: on
      charset: UTF-8
