spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://hostname/database?serverTimezone=UTC&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: xxxxxxxxx
    password: xxxxxxxxx
  security:
    user:
      name: xxxxxxxxx
      password: xxxxxxxxx
      roles:
        - USER
        - ADMIN

api:
  version: 1.0.0
  base: https://tomlin.no
  key: xxxxxxxxx
  tmdb:
    key: xxxxxxxxx
    url: https://api.themoviedb.org/3/
    img: https://image.tmdb.org/t/p/w200
  iata:
    airlines: https://raw.githubusercontent.com/opentraveldata/opentraveldata/master/opentraveldata/optd_airline_best_known_so_far.csv
    locations: https://raw.githubusercontent.com/opentraveldata/opentraveldata/master/opentraveldata/optd_por_public.csv
