spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://hostname/database?serverTimezone=UTC&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: xxxxxxxxx
    password: xxxxxxxxx
  security:
    user:
      name: xxxxxxxxx
      password: xxxxxxxxx
      roles:
        - USER
        - ADMIN

api:
  version: 1.0.0
  base: https://tomlin.no
  auth:
    key: xxxxxxxxx
  tmdb:
    key: xxxxxxxxx
  db:
    backup: -u user -ppassword database
